name: Build, Test & Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, test, pack, publish
    runs-on: ubuntu-latest
    timeout-minutes: 15    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release ./LibGame.sln --no-build
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output .
      - name: Publish
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}     
